// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheHnCNg9f-CDRazfe2ME7EePqe3se41o',
    appId: '1:978899320599:web:b62ec064038cece51c0152',
    messagingSenderId: '978899320599',
    projectId: 'tutorscribe-70f7b',
    authDomain: 'tutorscribe-70f7b.firebaseapp.com',
    storageBucket: 'tutorscribe-70f7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfP-byerVv2vI6NrvbmqKpOy7G0lPG-7Q',
    appId: '1:978899320599:android:1040fd8dce8925871c0152',
    messagingSenderId: '978899320599',
    projectId: 'tutorscribe-70f7b',
    storageBucket: 'tutorscribe-70f7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAueFnAqo-YiJ2oL0fbGsWPr6im3hxlInY',
    appId: '1:978899320599:ios:6488aec59d7717a01c0152',
    messagingSenderId: '978899320599',
    projectId: 'tutorscribe-70f7b',
    storageBucket: 'tutorscribe-70f7b.firebasestorage.app',
    iosClientId: '978899320599-ab5sgbaoc9fttng7n7b2lacpsgb3fugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAueFnAqo-YiJ2oL0fbGsWPr6im3hxlInY',
    appId: '1:978899320599:ios:6488aec59d7717a01c0152',
    messagingSenderId: '978899320599',
    projectId: 'tutorscribe-70f7b',
    storageBucket: 'tutorscribe-70f7b.firebasestorage.app',
    iosClientId: '978899320599-ab5sgbaoc9fttng7n7b2lacpsgb3fugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAheHnCNg9f-CDRazfe2ME7EePqe3se41o',
    appId: '1:978899320599:web:17f3d74e4d2986fd1c0152',
    messagingSenderId: '978899320599',
    projectId: 'tutorscribe-70f7b',
    authDomain: 'tutorscribe-70f7b.firebaseapp.com',
    storageBucket: 'tutorscribe-70f7b.firebasestorage.app',
  );

}